# Partir de l'image officielle Postgres
FROM postgres:16

# Définir variables d'environnement par défaut
ENV POSTGRES_USER=dlt_user
ENV POSTGRES_PASSWORD=secret
ENV POSTGRES_DB=dlt_db

# Copier des scripts d'initialisation (SQL ou sh) si tu veux précharger la DB
# Ils seront exécutés automatiquement au premier démarrage
#COPY init-scripts/ /docker-entrypoint-initdb.d/