# Image de base officielle
FROM python:3.11-slim

# Définit le dossier de travail
WORKDIR /app
COPY dltdata/requirements.txt .

# (Optionnel) installe les dépendances si requirements.txt existe
RUN pip install --no-cache-dir -r requirements.txt || true

# Commande par défaut
CMD ["dlt", "init"]